gui:
  theme:
    selectedLineBgColor:
      - "#414858"
  nerdFontsVersion: "3"
git:
  paging:
    colorArg: always
    pager: delta --dark --syntax-theme=TwoDark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
